"""
Alert Endpoints — Sprint 9.

REST API for querying alerts from Sprint 7's AlertManager.

Routes:
    GET /v1/venues/{venue_id}/alerts         → all alerts (active + resolved)
    GET /v1/venues/{venue_id}/alerts/active  → active alerts only
"""
from fastapi import APIRouter, Depends
from app.services.ai_engine_adapter import venue_registry
from app.services.intelligence_service import IntelligenceService
from app.schemas.intelligence import AlertListResponse

router = APIRouter(prefix="/v1/venues/{venue_id}/alerts", tags=["Alerts"])


def _get_intelligence_service() -> IntelligenceService:
    return IntelligenceService(venue_registry)


@router.get(
    "",
    response_model=AlertListResponse,
    summary="List all venue alerts",
    description="Returns all active and resolved anomaly alerts generated by Sprint 7 AlertManager.",
)
async def get_all_alerts(
    venue_id: str,
    svc: IntelligenceService = Depends(_get_intelligence_service),
):
    return svc.get_all_alerts(venue_id=venue_id)


@router.get(
    "/active",
    response_model=AlertListResponse,
    summary="List active venue alerts",
    description="Returns currently active alerts that have not yet subsided or been marked resolved.",
)
async def get_active_alerts(
    venue_id: str,
    svc: IntelligenceService = Depends(_get_intelligence_service),
):
    return svc.get_active_alerts(venue_id=venue_id)
